baseURL = "/"
languageCode = "en-US"

title = "iter8 Documentation"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

# See more parameters here: https://learn.netlify.app/en/basics/configuration/
[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page.
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  editURL = "https://github.com/iter8-tools/docs/edit/master/content/"

  # Author of the site, will be used in meta information
  author = "Alan Cha"

  # Description of the site, will be used in meta information
  description = "Robust analytics and control to unleash cloud-native continuous experimentation."

  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false

  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = true

  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = false

  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = true

  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]